# Generated by Django 5.2.7 on 2025-11-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priorty',
            field=models.CharField(choices=[('1', 'muxim'), ('2', 'sal muxim'), ('3', 'qilmasa ham boladi'), ('4', 'asosiy')], default='4'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
